# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spiderman.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1257, 1552)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.HCJ = QtGui.QTextBrowser(self.centralwidget)
        self.HCJ.setGeometry(QtCore.QRect(40, 670, 100, 65))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HCJ.sizePolicy().hasHeightForWidth())
        self.HCJ.setSizePolicy(sizePolicy)
        self.HCJ.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.HCJ.setFont(font)
        self.HCJ.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.HCJ.setObjectName(_fromUtf8("HCJ"))
        self.FT = QtGui.QTextBrowser(self.centralwidget)
        self.FT.setGeometry(QtCore.QRect(40, 860, 100, 65))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FT.sizePolicy().hasHeightForWidth())
        self.FT.setSizePolicy(sizePolicy)
        self.FT.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.FT.setFont(font)
        self.FT.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FT.setObjectName(_fromUtf8("FT"))
        self.YZ = QtGui.QTextBrowser(self.centralwidget)
        self.YZ.setGeometry(QtCore.QRect(50, 1000, 100, 195))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.YZ.sizePolicy().hasHeightForWidth())
        self.YZ.setSizePolicy(sizePolicy)
        self.YZ.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.YZ.setFont(font)
        self.YZ.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.YZ.setObjectName(_fromUtf8("YZ"))
        self.ICT = QtGui.QTextBrowser(self.centralwidget)
        self.ICT.setGeometry(QtCore.QRect(40, 440, 100, 65))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ICT.sizePolicy().hasHeightForWidth())
        self.ICT.setSizePolicy(sizePolicy)
        self.ICT.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ICT.setFont(font)
        self.ICT.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ICT.setObjectName(_fromUtf8("ICT"))
        self.SBJNG = QtGui.QTextBrowser(self.centralwidget)
        self.SBJNG.setGeometry(QtCore.QRect(450, 1280, 100, 65))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SBJNG.sizePolicy().hasHeightForWidth())
        self.SBJNG.setSizePolicy(sizePolicy)
        self.SBJNG.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SBJNG.setFont(font)
        self.SBJNG.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SBJNG.setObjectName(_fromUtf8("SBJNG"))
        self.SBJOK = QtGui.QTextBrowser(self.centralwidget)
        self.SBJOK.setGeometry(QtCore.QRect(40, 1280, 100, 65))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SBJOK.sizePolicy().hasHeightForWidth())
        self.SBJOK.setSizePolicy(sizePolicy)
        self.SBJOK.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SBJOK.setFont(font)
        self.SBJOK.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SBJOK.setObjectName(_fromUtf8("SBJOK"))
        self.JBT0 = QtGui.QTextBrowser(self.centralwidget)
        self.JBT0.setGeometry(QtCore.QRect(40, 150, 100, 65))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.JBT0.sizePolicy().hasHeightForWidth())
        self.JBT0.setSizePolicy(sizePolicy)
        self.JBT0.setMinimumSize(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.JBT0.setFont(font)
        self.JBT0.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.JBT0.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.JBT0.setObjectName(_fromUtf8("JBT0"))
        self.FT_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_AVAILABLE.setGeometry(QtCore.QRect(170, 860, 81, 23))
        self.FT_EVENT_AVAILABLE.setObjectName(_fromUtf8("FT_EVENT_AVAILABLE"))
        self.FT_EVENT_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_GETITEM_FINISHED.setGeometry(QtCore.QRect(270, 860, 81, 23))
        self.FT_EVENT_GETITEM_FINISHED.setObjectName(_fromUtf8("FT_EVENT_GETITEM_FINISHED"))
        self.FT_EVENT_TESTING = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_TESTING.setGeometry(QtCore.QRect(380, 860, 81, 23))
        self.FT_EVENT_TESTING.setObjectName(_fromUtf8("FT_EVENT_TESTING"))
        self.ICT_EVENT_READYFOR_SENDITEM_OK = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_READYFOR_SENDITEM_OK.setGeometry(QtCore.QRect(440, 440, 75, 23))
        self.ICT_EVENT_READYFOR_SENDITEM_OK.setObjectName(_fromUtf8("ICT_EVENT_READYFOR_SENDITEM_OK"))
        self.ICT_EVENT_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_GETITEM_FINISHED.setGeometry(QtCore.QRect(250, 440, 75, 23))
        self.ICT_EVENT_GETITEM_FINISHED.setObjectName(_fromUtf8("ICT_EVENT_GETITEM_FINISHED"))
        self.ICT_EVENT_READYFOR_SENDITEM_NG = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_READYFOR_SENDITEM_NG.setGeometry(QtCore.QRect(440, 480, 75, 23))
        self.ICT_EVENT_READYFOR_SENDITEM_NG.setObjectName(_fromUtf8("ICT_EVENT_READYFOR_SENDITEM_NG"))
        self.SBJOK_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.SBJOK_EVENT_AVAILABLE.setGeometry(QtCore.QRect(50, 1350, 75, 23))
        self.SBJOK_EVENT_AVAILABLE.setObjectName(_fromUtf8("SBJOK_EVENT_AVAILABLE"))
        self.SBJNG_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.SBJNG_EVENT_AVAILABLE.setGeometry(QtCore.QRect(460, 1350, 75, 23))
        self.SBJNG_EVENT_AVAILABLE.setObjectName(_fromUtf8("SBJNG_EVENT_AVAILABLE"))
        self.ICT_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_AVAILABLE.setGeometry(QtCore.QRect(160, 440, 75, 23))
        self.ICT_EVENT_AVAILABLE.setObjectName(_fromUtf8("ICT_EVENT_AVAILABLE"))
        self.JBT0_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.JBT0_EVENT_AVAILABLE.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.JBT0_EVENT_AVAILABLE.setObjectName(_fromUtf8("JBT0_EVENT_AVAILABLE"))
        self.JBT0_EVENT_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.JBT0_EVENT_GETITEM_FINISHED.setGeometry(QtCore.QRect(260, 150, 75, 23))
        self.JBT0_EVENT_GETITEM_FINISHED.setObjectName(_fromUtf8("JBT0_EVENT_GETITEM_FINISHED"))
        self.JBT0_EVENT_SENDITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.JBT0_EVENT_SENDITEM_FINISHED.setGeometry(QtCore.QRect(490, 150, 75, 23))
        self.JBT0_EVENT_SENDITEM_FINISHED.setObjectName(_fromUtf8("JBT0_EVENT_SENDITEM_FINISHED"))
        self.ICT_EVENT_TESTING = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_TESTING.setGeometry(QtCore.QRect(340, 440, 75, 23))
        self.ICT_EVENT_TESTING.setObjectName(_fromUtf8("ICT_EVENT_TESTING"))
        self.ICT_EVENT_SENDITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_SENDITEM_FINISHED.setGeometry(QtCore.QRect(570, 440, 75, 23))
        self.ICT_EVENT_SENDITEM_FINISHED.setObjectName(_fromUtf8("ICT_EVENT_SENDITEM_FINISHED"))
        self.ICT_EVENT_READYFOR_SENDITEM = QtGui.QPushButton(self.centralwidget)
        self.ICT_EVENT_READYFOR_SENDITEM.setGeometry(QtCore.QRect(440, 520, 111, 23))
        self.ICT_EVENT_READYFOR_SENDITEM.setObjectName(_fromUtf8("ICT_EVENT_READYFOR_SENDITEM"))
        self.HCJ_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.HCJ_EVENT_AVAILABLE.setGeometry(QtCore.QRect(170, 680, 75, 23))
        self.HCJ_EVENT_AVAILABLE.setObjectName(_fromUtf8("HCJ_EVENT_AVAILABLE"))
        self.HCJ_EVENT_HUANCUNJI_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.HCJ_EVENT_HUANCUNJI_GETITEM_FINISHED.setGeometry(QtCore.QRect(410, 680, 131, 23))
        self.HCJ_EVENT_HUANCUNJI_GETITEM_FINISHED.setObjectName(_fromUtf8("HCJ_EVENT_HUANCUNJI_GETITEM_FINISHED"))
        self.HCJ_EVENT_READYFOR_GETITEM_OK = QtGui.QPushButton(self.centralwidget)
        self.HCJ_EVENT_READYFOR_GETITEM_OK.setGeometry(QtCore.QRect(260, 680, 131, 23))
        self.HCJ_EVENT_READYFOR_GETITEM_OK.setObjectName(_fromUtf8("HCJ_EVENT_READYFOR_GETITEM_OK"))
        self.HCJ_EVENT_READYFOR_GETITEM_NG = QtGui.QPushButton(self.centralwidget)
        self.HCJ_EVENT_READYFOR_GETITEM_NG.setGeometry(QtCore.QRect(260, 720, 131, 23))
        self.HCJ_EVENT_READYFOR_GETITEM_NG.setObjectName(_fromUtf8("HCJ_EVENT_READYFOR_GETITEM_NG"))
        self.HCJ_EVENT_HUANCUNJI_NOTREADY = QtGui.QPushButton(self.centralwidget)
        self.HCJ_EVENT_HUANCUNJI_NOTREADY.setGeometry(QtCore.QRect(260, 760, 131, 23))
        self.HCJ_EVENT_HUANCUNJI_NOTREADY.setObjectName(_fromUtf8("HCJ_EVENT_HUANCUNJI_NOTREADY"))
        self.HCJ_EVENT_SENDITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.HCJ_EVENT_SENDITEM_FINISHED.setGeometry(QtCore.QRect(570, 680, 75, 23))
        self.HCJ_EVENT_SENDITEM_FINISHED.setObjectName(_fromUtf8("HCJ_EVENT_SENDITEM_FINISHED"))
        self.FT_EVENT_READYFOR_SENDITEM_OK = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_READYFOR_SENDITEM_OK.setGeometry(QtCore.QRect(490, 860, 75, 23))
        self.FT_EVENT_READYFOR_SENDITEM_OK.setObjectName(_fromUtf8("FT_EVENT_READYFOR_SENDITEM_OK"))
        self.FT_EVENT_READYFOR_SENDITEM_NG = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_READYFOR_SENDITEM_NG.setGeometry(QtCore.QRect(490, 900, 75, 23))
        self.FT_EVENT_READYFOR_SENDITEM_NG.setObjectName(_fromUtf8("FT_EVENT_READYFOR_SENDITEM_NG"))
        self.FT_EVENT_READYFOR_SENDITEM = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_READYFOR_SENDITEM.setGeometry(QtCore.QRect(490, 940, 111, 23))
        self.FT_EVENT_READYFOR_SENDITEM.setObjectName(_fromUtf8("FT_EVENT_READYFOR_SENDITEM"))
        self.SBJOK_EVENT_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.SBJOK_EVENT_GETITEM_FINISHED.setGeometry(QtCore.QRect(50, 1380, 75, 23))
        self.SBJOK_EVENT_GETITEM_FINISHED.setObjectName(_fromUtf8("SBJOK_EVENT_GETITEM_FINISHED"))
        self.SBJNG_EVENT_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.SBJNG_EVENT_GETITEM_FINISHED.setGeometry(QtCore.QRect(460, 1380, 75, 23))
        self.SBJNG_EVENT_GETITEM_FINISHED.setObjectName(_fromUtf8("SBJNG_EVENT_GETITEM_FINISHED"))
        self.YZ_EVENT_SENDITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.YZ_EVENT_SENDITEM_FINISHED.setGeometry(QtCore.QRect(610, 1050, 131, 23))
        self.YZ_EVENT_SENDITEM_FINISHED.setObjectName(_fromUtf8("YZ_EVENT_SENDITEM_FINISHED"))
        self.YZ_EVENT_AVAILABLE = QtGui.QPushButton(self.centralwidget)
        self.YZ_EVENT_AVAILABLE.setGeometry(QtCore.QRect(170, 1050, 161, 23))
        self.YZ_EVENT_AVAILABLE.setObjectName(_fromUtf8("YZ_EVENT_AVAILABLE"))
        self.YZ_EVENT_GETITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.YZ_EVENT_GETITEM_FINISHED.setGeometry(QtCore.QRect(510, 1050, 91, 23))
        self.YZ_EVENT_GETITEM_FINISHED.setObjectName(_fromUtf8("YZ_EVENT_GETITEM_FINISHED"))
        self.YZ_EVENT_READYFOR_GETITEM_RIGHT = QtGui.QPushButton(self.centralwidget)
        self.YZ_EVENT_READYFOR_GETITEM_RIGHT.setGeometry(QtCore.QRect(360, 1050, 131, 23))
        self.YZ_EVENT_READYFOR_GETITEM_RIGHT.setObjectName(_fromUtf8("YZ_EVENT_READYFOR_GETITEM_RIGHT"))
        self.JBT0_EVENT_READYFOR_SENDITEM = QtGui.QPushButton(self.centralwidget)
        self.JBT0_EVENT_READYFOR_SENDITEM.setGeometry(QtCore.QRect(370, 150, 75, 23))
        self.JBT0_EVENT_READYFOR_SENDITEM.setObjectName(_fromUtf8("JBT0_EVENT_READYFOR_SENDITEM"))
        self.FT_EVENT_SENDITEM_FINISHED = QtGui.QPushButton(self.centralwidget)
        self.FT_EVENT_SENDITEM_FINISHED.setGeometry(QtCore.QRect(620, 860, 75, 23))
        self.FT_EVENT_SENDITEM_FINISHED.setObjectName(_fromUtf8("FT_EVENT_SENDITEM_FINISHED"))
        self.log = QtGui.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(740, 150, 256, 781))
        self.log.setObjectName(_fromUtf8("log"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1257, 29))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.START_2 = QtGui.QAction(MainWindow)
        self.START_2.setObjectName(_fromUtf8("START_2"))
        self.menu.addAction(self.START_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.FT_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.FT_EVENT_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.FT_EVENT_TESTING, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.ICT_EVENT_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.ICT_EVENT_READYFOR_SENDITEM_OK, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.ICT_EVENT_READYFOR_SENDITEM_NG, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.SBJNG_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.SBJOK_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.ICT_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.JBT0_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.JBT0_EVENT_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.JBT0_EVENT_SENDITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.ICT_EVENT_READYFOR_SENDITEM, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.ICT_EVENT_SENDITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.HCJ_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.HCJ_EVENT_READYFOR_GETITEM_OK, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.HCJ_EVENT_READYFOR_GETITEM_NG, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.HCJ_EVENT_HUANCUNJI_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.HCJ_EVENT_HUANCUNJI_NOTREADY, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.HCJ_EVENT_SENDITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.FT_EVENT_READYFOR_SENDITEM_OK, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.FT_EVENT_READYFOR_SENDITEM_NG, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.FT_EVENT_READYFOR_SENDITEM, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.SBJOK_EVENT_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.SBJNG_EVENT_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.YZ_EVENT_AVAILABLE, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.YZ_EVENT_GETITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.YZ_EVENT_SENDITEM_FINISHED, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QObject.connect(self.JBT0_EVENT_READYFOR_SENDITEM, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.send_msg_to_server)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.HCJ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">缓存机</span></p></body></html>", None))
        self.FT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">FT测试</span></p></body></html>", None))
        self.YZ.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">移</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-weight:600; color:#ffffff;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">载</span></p></body></html>", None))
        self.ICT.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">ICT测试</span></p></body></html>", None))
        self.SBJNG.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">NG收板</span></p></body></html>", None))
        self.SBJOK.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:400; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-weight:600; color:#ffffff;\">OK收板</span></p></body></html>", None))
        self.JBT0.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'PMingLiU\'; font-size:16pt; font-weight:600; font-style:normal;\" bgcolor=\"#000000\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:9pt; font-weight:400;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; color:#ffffff;\">接驳台0</span></p></body></html>", None))
        self.FT_EVENT_AVAILABLE.setText(_translate("MainWindow", "空闲/正常", None))
        self.FT_EVENT_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.FT_EVENT_TESTING.setText(_translate("MainWindow", "测试中", None))
        self.ICT_EVENT_READYFOR_SENDITEM_OK.setText(_translate("MainWindow", "测试OK", None))
        self.ICT_EVENT_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.ICT_EVENT_READYFOR_SENDITEM_NG.setText(_translate("MainWindow", "测试NG", None))
        self.SBJOK_EVENT_AVAILABLE.setText(_translate("MainWindow", "正常/空闲", None))
        self.SBJNG_EVENT_AVAILABLE.setText(_translate("MainWindow", "正常/空闲", None))
        self.ICT_EVENT_AVAILABLE.setText(_translate("MainWindow", "空闲/正常", None))
        self.JBT0_EVENT_AVAILABLE.setText(_translate("MainWindow", "空闲", None))
        self.JBT0_EVENT_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.JBT0_EVENT_SENDITEM_FINISHED.setText(_translate("MainWindow", "送板完成", None))
        self.ICT_EVENT_TESTING.setText(_translate("MainWindow", "测试中", None))
        self.ICT_EVENT_SENDITEM_FINISHED.setText(_translate("MainWindow", "送板完成", None))
        self.ICT_EVENT_READYFOR_SENDITEM.setText(_translate("MainWindow", "准备送板(无测试)", None))
        self.HCJ_EVENT_AVAILABLE.setText(_translate("MainWindow", "空闲/正常", None))
        self.HCJ_EVENT_HUANCUNJI_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.HCJ_EVENT_READYFOR_GETITEM_OK.setText(_translate("MainWindow", "准备好接OK板", None))
        self.HCJ_EVENT_READYFOR_GETITEM_NG.setText(_translate("MainWindow", "准备好接NG板", None))
        self.HCJ_EVENT_HUANCUNJI_NOTREADY.setText(_translate("MainWindow", "缓存机未准备好", None))
        self.HCJ_EVENT_SENDITEM_FINISHED.setText(_translate("MainWindow", "送板完成", None))
        self.FT_EVENT_READYFOR_SENDITEM_OK.setText(_translate("MainWindow", "测试OK", None))
        self.FT_EVENT_READYFOR_SENDITEM_NG.setText(_translate("MainWindow", "测试NG", None))
        self.FT_EVENT_READYFOR_SENDITEM.setText(_translate("MainWindow", "准备送板(无测试)", None))
        self.SBJOK_EVENT_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.SBJNG_EVENT_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.YZ_EVENT_SENDITEM_FINISHED.setText(_translate("MainWindow", "送板完成", None))
        self.YZ_EVENT_AVAILABLE.setText(_translate("MainWindow", "空闲", None))
        self.YZ_EVENT_GETITEM_FINISHED.setText(_translate("MainWindow", "接板完成", None))
        self.YZ_EVENT_READYFOR_GETITEM_RIGHT.setText(_translate("MainWindow", "到达右边", None))
        self.JBT0_EVENT_READYFOR_SENDITEM.setText(_translate("MainWindow", "准备送板", None))
        self.FT_EVENT_SENDITEM_FINISHED.setText(_translate("MainWindow", "送板完成", None))
        self.menu.setTitle(_translate("MainWindow", "菜单", None))
        self.START_2.setText(_translate("MainWindow", "开机", None))

